{
 "title": "Dittybopper - Master Nodes",
 "description": "Performance dashboard for Red Hat OpenShift",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load : master0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master0\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master0\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master0\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Load : master1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master1\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master1\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master1\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Load : master2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master2\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master2\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master2\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "CPU Basic : master0",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master0\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master0\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master0\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master0\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master0\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master0\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : master1",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master1\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master1\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master1\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master1\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master1\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master1\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : master2",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master2\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master2\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master2\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master2\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master2\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master2\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "System Memory : master0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"master0\",job=~\".*\"})",
     "legendFormat": "Total Physical"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=~\"master0\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master0\",job=~\".*\"})",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "sum(node_memory_Dirty_bytes{instance=~\"master0\",job=~\".*\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum(node_memory_AnonPages_bytes{instance=~\"master0\",job=~\".*\"})",
     "legendFormat": "Anon Pages"
    },
    {
     "expr": "sum(node_memory_Slab_bytes{instance=~\"master0\",job=~\".*\"})",
     "legendFormat": "Kernel Slab"
    },
    {
     "expr": "sum(node_memory_VmallocUsed_bytes{instance=~\"master0\",job=~\".*\"})",
     "legendFormat": "VM Alloc Used"
    }
   ]
  },
  {
   "title": "System Memory : master1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"master1\",job=~\".*\"})",
     "legendFormat": "Total Physical"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=~\"master1\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master1\",job=~\".*\"})",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "sum(node_memory_Dirty_bytes{instance=~\"master1\",job=~\".*\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum(node_memory_AnonPages_bytes{instance=~\"master1\",job=~\".*\"})",
     "legendFormat": "Anon Pages"
    },
    {
     "expr": "sum(node_memory_Slab_bytes{instance=~\"master1\",job=~\".*\"})",
     "legendFormat": "Kernel Slab"
    },
    {
     "expr": "sum(node_memory_VmallocUsed_bytes{instance=~\"master1\",job=~\".*\"})",
     "legendFormat": "VM Alloc Used"
    }
   ]
  },
  {
   "title": "System Memory : master2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"master2\",job=~\".*\"})",
     "legendFormat": "Total Physical"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=~\"master2\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master2\",job=~\".*\"})",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "sum(node_memory_Dirty_bytes{instance=~\"master2\",job=~\".*\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum(node_memory_AnonPages_bytes{instance=~\"master2\",job=~\".*\"})",
     "legendFormat": "Anon Pages"
    },
    {
     "expr": "sum(node_memory_Slab_bytes{instance=~\"master2\",job=~\".*\"})",
     "legendFormat": "Kernel Slab"
    },
    {
     "expr": "sum(node_memory_VmallocUsed_bytes{instance=~\"master2\",job=~\".*\"})",
     "legendFormat": "VM Alloc Used"
    }
   ]
  },
  {
   "title": "Disk Throughput : master0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master0\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master0\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput : master1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master1\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master1\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput : master2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master2\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master2\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : master0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master0\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master0\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : master1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master1\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master1\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : master2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master2\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master2\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Network Utilization : master0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master0\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master0\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization : master1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master1\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master1\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization : master2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master2\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master2\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Process RSS : master0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{instance=\"master0:10250\"}",
     "legendFormat": "{{ job_name }} - {{ container_name }}"
    }
   ]
  },
  {
   "title": "Process RSS : master1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{instance=\"master1:10250\"}",
     "legendFormat": "{{ job_name }} - {{ container_name }}"
    }
   ]
  },
  {
   "title": "Process RSS : master2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{instance=\"master2:10250\"}",
     "legendFormat": "{{ job_name }} - {{ container_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage : master0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master0:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU Usage : master1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master1:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU Usage : master2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master2:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  }
 ]
}