{
 "title": "OpenShift Cluster Performance Dashboard",
 "description": "Performance dashboards for Red Hat OpenShift",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "_node",
    "label": "masters",
    "query": "query_result(  kube_node_role{role=\"master\",prometheus_replica=\"prometheus-k8s-0\", clustername=~\"$clustername\"} )"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   },
   {
    "name": "clustername",
    "query": "label_values(process_cpu_seconds_total,clustername)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$clustername - API Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,service) (rate(apiserver_request_count{clustername=~\"$clustername\"}[5m]))",
       "legendFormat": "{{service}} - {{instance}}"
      }
     ]
    },
    {
     "title": "$clustername Goroutines Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(go_goroutines{clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}) by (job,instance))",
       "legendFormat": "{{job}} - {{instance}}"
      }
     ]
    },
    {
     "title": "$clustername - api CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{clustername=~\"$clustername\",namespace=~\"api\",id=~\"slice$\",prometheus_replica=\"prometheus-k8s-0\"}[5m])",
       "legendFormat": "{{node}} - {{pod}}"
      }
     ]
    },
    {
     "title": "$clustername api RSS memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{clustername=~\"$clustername\",namespace=~\"api\",prometheus_replica=~\"prometheus-k8s-0\",id=~\"slice$\"}",
       "legendFormat": "{{node}} - {{pod_name}}"
      }
     ]
    },
    {
     "title": "$clustername - etcd CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{clustername=~\"$clustername\",namespace=~\"etcd\",id=~\"slice$\",prometheus_replica=\"prometheus-k8s-0\"}[5m])",
       "legendFormat": "{{node}} - {{pod}}"
      }
     ]
    },
    {
     "title": "$clustername etcd RSS memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{clustername=~\"$clustername\",namespace=~\"etcd\",prometheus_replica=~\"prometheus-k8s-0\",id=~\"slice$\"}",
       "legendFormat": "{{node}} - {{pod_name}}"
      }
     ]
    },
    {
     "title": "$clustername pod count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\",clustername=~\"$clustername\"})",
       "legendFormat": "Running Pods"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\",clustername=~\"$clustername\"})",
       "legendFormat": "Succeeded Pods"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Failed\",clustername=~\"$clustername\"})",
       "legendFormat": "Failed Pods"
      }
     ]
    },
    {
     "title": "$clustername Namespace Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_namespace_created{clustername=~\"$clustername\"})",
       "legendFormat": "Namespace Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Master : $_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "_node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic : $_node",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "System Memory : $_node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"} + node_memory_Buffers_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"} - (node_memory_Cached_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"} + node_memory_Buffers_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk Throughput : $_node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS : $_node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - write"
      }
     ]
    },
    {
     "title": "Network Utilization : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$$_node\",device=~\"$net_device\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$_node\",device=~\"$net_device\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets/s : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$$_node\",device=~\"$net_device\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$_node\",device=~\"$net_device\",clustername=~\"$clustername\",prometheus_replica=\"prometheus-k8s-0\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Container CPU Usage : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{node=~\"$_node\",clustername=~\"$clustername\",namespace=~\"$namespace\",id=~\"slice$\",prometheus_replica=\"prometheus-k8s-0\"}[5m])",
       "legendFormat": "{{ pod_name }} - {{ service }}"
      }
     ]
    },
    {
     "title": "Process RSS :$_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{node=~\"$_node\",clustername=~\"$clustername\",namespace=~\"$namespace\",prometheus_replica=~\"prometheus-k8s-0\",id=~\"slice$\"}",
       "legendFormat": "{{pod_name}} - {{ node }}"
      }
     ]
    }
   ]
  }
 ]
}