name: Jsonnet CI
defaults:
  run:
    shell: bash
    working-directory: jsonnet

on:
  push:
    branches: [ master ]
    paths: jsonnet/templates/**
  pull_request:
    branches: [ master ]
    paths: jsonnet/templates/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile dashboards
      run: make build

  lint:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Get dependencies
      run: make deps
    
    - name: Run jsonnetfmt
      run: ./bin/jsonnetfmt --test templates/*.jsonnet

